substitutions:
  _REGION: asia-south1
  _PROJECT_ID: thums-up-project-id
  _REPO_NAME: thums-up-cloud-build-repo
  _SUBSCRIBER_SERVICE: thums-up-cloudrun-subscriber

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_SUBSCRIBER_SERVICE}:latest || exit 0']
    id: 'pull-cache'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'Dockerfile.subscriber',
        '-t',
        '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_SUBSCRIBER_SERVICE}:$SHORT_SHA',
        '-t',
        '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_SUBSCRIBER_SERVICE}:latest',
        '--cache-from',
        '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_SUBSCRIBER_SERVICE}:latest',
        '.'
      ]
    id: 'build-image'
    waitFor: ['pull-cache']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_SUBSCRIBER_SERVICE}:$SHORT_SHA'
      ]
    id: 'push-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_SUBSCRIBER_SERVICE}:latest'
      ]
    id: 'push-latest'
    waitFor: ['build-image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '${_SUBSCRIBER_SERVICE}',
        '--image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_SUBSCRIBER_SERVICE}:$SHORT_SHA',
        '--region=${_REGION}',
        '--platform=managed',
        '--execution-environment=gen2',
        '--min-instances=1',
        '--max-instances=3',
        '--no-allow-unauthenticated',
        '--cpu=2',
        '--memory=1Gi',
        '--service-account=thums-up-cloudrun-sa@${_PROJECT_ID}.iam.gserviceaccount.com',
        '--set-secrets=GOOGLE_PUBSUB_PROJECT_ID=GOOGLE_PUBSUB_PROJECT_ID:latest,GOOGLE_PUBSUB_SUBSCRIPTION_ID=GOOGLE_PUBSUB_SUBSCRIPTION_ID:latest,GOOGLE_PUBSUB_TOPIC_ID=GOOGLE_PUBSUB_TOPIC_ID:latest,X_API_KEY=X_API_KEY:latest,GCP_BUCKET_NAME=GCP_BUCKET_NAME:latest,GCP_PROJECT_ID=GCP_PROJECT_ID:latest'
      ]
    id: 'deploy-cloudrun'
    waitFor: ['push-sha', 'push-latest']

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_SUBSCRIBER_SERVICE}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_SUBSCRIBER_SERVICE}:latest'

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

